//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssigmentDeneme.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Urun
    {
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public string UrunAciklama { get; set; }
        public string UrunStok { get; set; }
        public string UrunFiyat { get; set; }
        [DisplayName("Resim Seçiniz")]
        public string UrunResim { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
